"""
Keyword-based financial sentiment scoring.

Lightweight lexicon-based sentiment for fast baselines and benchmarking.
"""

from __future__ import annotations

import re
from typing import Tuple

# Financial sentiment lexicon - curated for financial text
_POSITIVE_WORDS = {
    "surge",
    "surges",
    "surging",
    "surged",
    "soar",
    "soars",
    "soaring",
    "soared",
    "rally",
    "rallies",
    "rallied",
    "rallying",
    "gain",
    "gains",
    "gained",
    "rise",
    "rises",
    "rising",
    "rose",
    "jump",
    "jumps",
    "jumped",
    "jumping",
    "climb",
    "climbs",
    "climbed",
    "climbing",
    "boom",
    "booming",
    "boomed",
    "bullish",
    "bull",
    "upbeat",
    "optimistic",
    "optimism",
    "outperform",
    "beat",
    "beats",
    "beating",
    "exceeded",
    "exceeds",
    "exceeding",
    "profit",
    "profits",
    "profitable",
    "profitability",
    "revenue",
    "growth",
    "growing",
    "grew",
    "expand",
    "expanding",
    "strong",
    "stronger",
    "strongest",
    "strength",
    "upgrade",
    "upgraded",
    "upgrades",
    "buy",
    "overweight",
    "record",
    "high",
    "highs",
    "breakout",
    "breakthrough",
    "positive",
    "upside",
    "momentum",
    "acceleration",
    "recover",
    "recovers",
    "recovered",
    "recovery",
    "dividend",
    "buyback",
    "buybacks",
    "repurchase",
    "innovation",
    "innovative",
    "opportunity",
    "opportunities",
    "success",
    "successful",
    "win",
    "wins",
    "winning",
    "demand",
    "robust",
    "solid",
    "impressive",
    "impressive",
    "outpace",
    "outpaced",
    "exceeds",
    "fantastic",
    "excellent",
}

_NEGATIVE_WORDS = {
    "crash",
    "crashes",
    "crashed",
    "crashing",
    "plunge",
    "plunges",
    "plunged",
    "plunging",
    "drop",
    "drops",
    "dropped",
    "dropping",
    "fall",
    "falls",
    "fell",
    "falling",
    "decline",
    "declines",
    "declined",
    "declining",
    "loss",
    "losses",
    "lost",
    "losing",
    "miss",
    "misses",
    "missed",
    "missing",
    "bearish",
    "bear",
    "pessimistic",
    "pessimism",
    "sell",
    "selling",
    "selloff",
    "sell-off",
    "downgrade",
    "downgraded",
    "downgrades",
    "underweight",
    "cut",
    "cuts",
    "slashed",
    "reduce",
    "reduced",
    "weak",
    "weaker",
    "weakest",
    "weakness",
    "risk",
    "risks",
    "risky",
    "volatile",
    "volatility",
    "debt",
    "deficit",
    "bankruptcy",
    "bankrupt",
    "layoff",
    "layoffs",
    "fired",
    "restructuring",
    "lawsuit",
    "sued",
    "investigation",
    "probe",
    "scandal",
    "warning",
    "warns",
    "warned",
    "caution",
    "cautious",
    "fear",
    "fears",
    "panic",
    "concern",
    "concerns",
    "worried",
    "inflation",
    "recession",
    "downturn",
    "slowdown",
    "overvalued",
    "bubble",
    "fraud",
    "default",
    "underperform",
    "disappoint",
    "disappointing",
    "disappointed",
    "struggle",
    "struggles",
    "struggling",
    "tumble",
    "tumbles",
    "tumbled",
    "tank",
    "tanks",
    "tanked",
    "worst",
    "terrible",
    "awful",
    "disaster",
}


def calculate_financial_sentiment(text: str) -> Tuple[str, float]:
    """
    Calculate sentiment using a financial keyword lexicon (fast mode).
    Returns (label, confidence_score).
    """
    words = set(re.findall(r"\b[a-z]+\b", text.lower()))

    pos_count = len(words & _POSITIVE_WORDS)
    neg_count = len(words & _NEGATIVE_WORDS)
    total = pos_count + neg_count

    if total == 0:
        return "neutral", 0.5

    net_score = (pos_count - neg_count) / total

    if net_score > 0.15:
        confidence = min(0.95, 0.6 + (pos_count / max(total, 1)) * 0.3)
        return "positive", round(confidence, 4)
    if net_score < -0.15:
        confidence = min(0.95, 0.6 + (neg_count / max(total, 1)) * 0.3)
        return "negative", round(confidence, 4)

    return "neutral", round(0.5 + abs(net_score) * 0.2, 4)
