import React from 'react';
import { Link } from 'react-router-dom';
import Navbar from '../../components/Navbar';
import '../StockAnalysis/StockAnalysis.css';
import './Legal.css';

export default function Legal() {
  return (
    <div id="main-content" className="legal-page stock-analysis" tabIndex={-1}>
      <Navbar
        title="Legal & disclaimer"
        subtitle="How to interpret this product, data, and AI-generated content."
        siteNav
      />
      <article className="legal-page__article">
        <h2 className="legal-page__h2">Not financial advice</h2>
        <p>
          This dashboard is provided for <strong>informational and educational</strong> purposes only. Nothing
          here is an offer, solicitation, or recommendation to buy or sell any security, derivative, or other
          instrument. You alone are responsible for investment and trading decisions.
        </p>

        <h2 className="legal-page__h2">Data &amp; models</h2>
        <p>
          Sentiment labels come from automated classifiers (e.g. FinBERT) on text collected from third-party
          sources such as Reddit, news APIs, and public social posts. Labels can be wrong, incomplete, or
          outdated. Mention counts, correlations, and &ldquo;data quality&rdquo; scores are{' '}
          <strong>heuristic summaries</strong> of ingested content — not audited fundamentals or market data
          from an exchange.
        </p>

        <h2 className="legal-page__h2">AI narrative</h2>
        <p>
          Ticker narratives are generated by a large language model from sampled records. They may omit
          context, hallucinate, or reflect biases in the training data or prompt. Always treat AI output as a
          starting point for review, not a substitute for your own analysis or professional advice.
        </p>

        <h2 className="legal-page__h2">No warranties</h2>
        <p>
          The service is provided &ldquo;as is&rdquo; without warranties of accuracy, availability, or fitness
          for a particular purpose. Outages, ingestion gaps, and upstream API changes can affect charts and
          statistics without notice.
        </p>

        <h2 className="legal-page__h2">Enterprise deployment</h2>
        <p>
          For production use, configure HTTPS, restrict CORS to your front-end origins, and set{' '}
          <code className="legal-page__code">API_KEYS</code> on the backend with matching{' '}
          <code className="legal-page__code">VITE_API_KEY</code> at build time for the SPA. Use{' '}
          <code className="legal-page__code">/health</code> for liveness and{' '}
          <code className="legal-page__code">/health/ready</code> for database readiness checks.
        </p>

        <p className="legal-page__back">
          <Link to="/methodology" className="legal-page__back-link">
            Methodology &amp; evaluation framing
          </Link>
          {' · '}
          <Link to="/" className="legal-page__back-link">
            ← Market overview
          </Link>
        </p>
      </article>
    </div>
  );
}
